apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    {{- include "certchain-org.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  realm.json: |
{{ .Files.Get (printf "files/realm-%s.json" .Values.org.name) | indent 4 }}
