FROM registry.access.redhat.com/ubi9/nodejs-22:latest AS build
USER 0
WORKDIR /opt/app-root/src
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nodejs-22-minimal:latest
USER 0
WORKDIR /opt/app-root/src
COPY --from=build /opt/app-root/src/dist ./dist
COPY --from=build /opt/app-root/src/server.js ./server.js
COPY --from=build /opt/app-root/src/package.json ./package.json
RUN npm install --omit=dev && chown -R 1001:0 /opt/app-root/src
USER 1001
EXPOSE 8080
CMD ["node", "server.js"]
