site:
  title: "CertChain — Blockchain Credentialing Demo"
  start_page: certchain::index.adoc

content:
  sources:
    - url: /showroom/repo
      start_path: showroom/content

asciidoc:
  attributes:
    experimental: true
    idprefix: ""
    idseparator: "-"

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-summit-connect-2025/ui-bundle.zip
    snapshot: true
