site:
  title: "CertChain — Blockchain Credentialing Demo"
  start_page: certchain::index.adoc

content:
  sources:
    - url: /showroom/repo
      start_path: showroom/content

asciidoc:
  attributes:
    experimental: true
    idprefix: ""
    idseparator: "-"

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-summit-connect-2025/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: partials/header-content.hbs
      contents: |
        <header class="header">
          <nav class="navbar">
            <div class="navbar-brand">
              <a class="navbar-item" href="https://www.redhat.com" target="_blank" rel="noopener" style="margin-left: 5%;">
                <img src="{{uiRootPath}}/img/header_logo.png" alt="Red Hat Summit Connect" style="height:46px">
              </a>
              <a class="navbar-item site-title" target="__blank" style="color: #fff !important;" href="{{{or site.url (or siteRootUrl siteRootPath)}}}">{{site.title}}</a>
            </div>
            <div id="topbar-nav" class="navbar-menu">
              <div class="navbar-end">
                {{#if page.attributes.user}}
                <div class="navbar-item">You are {{page.attributes.user}}</div>
                {{/if}}
              </div>
            </div>
          </nav>
        </header>
