apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-central
  labels:
    {{- include "certchain-central.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  realm-central.json: |
{{ .Files.Get "files/realm-central.json" | indent 4 }}
